package: github_repo
version: '1.0.0'
author: Ali Kemal Tuncel

page:
  hidden: true

requires:
    redaxo: '^5.14'
    php:
      version: '>=8.1'
    packages:
       feeds: '>=4.0.0-dev'

conflicts:
    packages:
        yfeed: '<=1.3.0'
        feeds: '<4.0.0-dev'